[features]
seeds = false
skip-lint = false

[programs.devnet]
staking_vault = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
referral_tracker = "Gg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./token-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"