[features]
seeds = false
skip-lint = false

[programs.devnet]
staking_vault = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
referral_tracker = "Gg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnH"
[programs.localnet]
staking_vault = "programs/staking_vault"
referral_tracker = "programs/referral_tracker"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./token-keypair.json"
[toolchain]
    anchor_version = "0.29.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"