
[features]
seeds = false
skip-lint = false

[programs.devnet]
# Using the deployed program ID from Solana Playground
staking_vault = "EnGhdovdYhHk4nsHEJr6gmV5cYfrx53ky19RD56eRRGm"
referral_tracker = "59TF7G5NqMdqjHvpsBPojuhvksHiHVUkaNkaiVvozDrk"

[programs.localnet]
staking_vault = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
referral_tracker = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./token-keypair.json"

[toolchain]
anchor_version = "0.26.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
